### ISSUE TITLE
[Bug] Absoltue file path on minju branch

### ISSUE THREAD

**Issue by theorist17** [convei-lab/ParlAI#1]
**Bug description**
파일 경로들이 절대경로라서 파일을 열수가 없어!

**Reproduction steps**
병합하고 실행하니까 안됨.

**Expected behavior**
4번 스크립트 실행하고 싶어

**Logs**
Please paste the command line output:

```
[ loading contexts.. ]
13:04:32 | building data: /data3/theorist/ParlAI/data/pbst
Parsing ConvAI2 on /data3/theorist/ParlAI/data/pbst/convai2/train_both_original_no_cands.txt
17878 contexts and seed utterances pairs were parsed from the convai2

Parsing wizard_of_wikipedia on /data3/theorist/ParlAI/data/pbst/wizard_of_wikipedia/train.json
Parsing wizard_of_wikipedia on /data3/theorist/ParlAI/data/pbst/wizard_of_wikipedia/valid_random_split.json
19411 contexts and seed utterances pairs were parsed from the wizard_of_wikipedia

Parsing empatheticdialogues on /data3/theorist/ParlAI/data/pbst/empatheticdialogues/train.csv
Parsing empatheticdialogues on /data3/theorist/ParlAI/data/pbst/empatheticdialogues/valid.csv
22300 contexts and seed utterances pairs were parsed from the empatheticdialogues

Traceback (most recent call last):
  File "/home/common/miniconda3/envs/blending-hi/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/data3/theorist/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/data3/theorist/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/data3/theorist/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/data3/theorist/ParlAI/parlai/scripts/self_mix.py", line 199, in run
    return self_mix(self.opt)
  File "/data3/theorist/ParlAI/parlai/scripts/self_mix.py", line 161, in self_mix
    world = world_class(opt, expert_agents)
  File "/data3/theorist/ParlAI/parlai/tasks/self_mix/worlds.py", line 70, in __init__
    self.init_contexts(shared=shared)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/worlds.py", line 164, in init_contexts
    self.contexts_data = get_contexts_data(self.opt, shared=shared)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/worlds.py", line 20, in get_contexts_data
    return _load_personas(opt=opt)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/worlds.py", line 25, in _load_personas
    fname = raw_data_path(opt)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/agents.py", line 17, in raw_data_path
    build(opt)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/build.py", line 81, in build
    context = _build_contextual_document(opt, subtaskpaths)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/build.py", line 475, in _build_contextual_document
    leading_doc_ids = _retrieve_contextual_document(leading_seeds, leading_contexts, 'lexical', target)
  File "/data3/theorist/ParlAI/parlai/tasks/pbst/build.py", line 408, in _retrieve_contextual_document
    with open(parlai_data_path + split[0] + '/retrieval.json', "w") as json_file:
PermissionError: [Errno 13] Permission denied: '/home/minju/data1/ParlAI/data/topic_inference/retrieval.json'
```

**Additional context**
경로 고치고 여기 리모트 minju 브랜치에 올려줘~.

**Comment by theorist17** [comment]
/data3/theorist/ParlAI/parlai/tasks/pbst/build.py 이 파일에 [314번째 줄](https://github.com/convei-lab/ParlAI/blob/6c0258de14ff52c68c764b36d429bab71dfb2331/parlai/tasks/pbst/build.py#L314)도 상대경로예용.

**Comment by theorist17** [comment]
[여기](https://github.com/convei-lab/ParlAI/blob/6c0258de14ff52c68c764b36d429bab71dfb2331/parlai/tasks/pbst/build.py#L329)도
